Style/Documentation:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false
  
ClassLength:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false
  
AsciiComments:
  Enabled: false
  
BlockLength:
  Enabled: false
  
Style/NumericPredicate:
  EnforcedStyle: comparison